blog/urls.py
from . import views
from django.urls import path
from .views import (
        PostDeleteView,
        UserPostListView,
        CatPostListView, 
        NewPostView,
    )

urlpatterns = [
    path('', views.index, name="Blog-Home"),
    path('post/<str:username>/user/', UserPostListView.as_view(), name="Blog-User"),
    path('post/<str:category>/category/', CatPostListView.as_view(), name="Blog-Cat"),
    path('post/<int:pk>/details/', views.PostDetail, name="Blog-details"),
    path('post/<int:pk>/update/', views.UpdatePost, name="Blog-Update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="Blog-Delete"),
    # path('post/new/', views.newPost, name="Blog-create"),
    path('post/new/', NewPostView.as_view(), name="Blog-create"),

    path('post/about/', views.about, name="Blog-About"),
] 

eblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from  django.contrib.auth.models import User


class Category(models.Model):
    CatName = models.CharField(max_length=100)
    def __str__(self):
        return self.CatName

class Posts(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, default="1", on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='blog_pics')
 
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Blog-details", kwargs={"pk": self.id})
    
 

blog/forms.py
from django import forms
from .models import Posts, Category

class NewPostForm(forms.ModelForm):    
    class Meta:
        model = Posts
        fields = ['title', 'category', 'content', 'image']


class CatPostForm(forms.ModelForm): 
    class Meta: 
        model=Category
        fields = ['CatName']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
import json
from django.contrib.auth.models import User
from .models import Posts, Category
from .forms import CatPostForm, NewPostForm
from django.views.generic import (
    ListView, 
    DetailView, 
    UpdateView,
    CreateView,
    DeleteView,
    TemplateView
)

pagNum = 3

def about(request):
    return render(request, 'blog/about.html', {})

class UserPostListView(ListView):
    model = Posts
    template_name = 'blog/UserPosts.html'
    context_object_name = 'posts'
    paginate_by = pagNum

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Posts.objects.filter(author=user).order_by('-date_posted')

class CatPostListView(ListView):
    model = Posts
    template_name = 'blog/CatPosts.html'
    context_object_name = 'posts'
    paginate_by = pagNum

    def get_queryset(self):
        DeyId = get_object_or_404(Category, CatName=self.kwargs.get('category'))  
        return Posts.objects.filter(category_id=DeyId).order_by('-date_posted') 

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Posts
    success_url = '/'
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

@login_required
def newPost(request):    
    deyCat = Category.objects.all() 
    if request.method =='POST':
        myForm = NewPostForm(request.POST, request.FILES)
        response_data = {
            'SType': 'danger',
            'message': "An Error Occured, pls try again later"
        }
        if request.POST.get('deyHidden') == 'create_hidden':
            title = request.POST.get('title')
            content = request.POST.get('content')
            category_id = request.POST.get('category')
            image = request.FILES.get('image') 
            if myForm.is_valid():
                if Posts.objects.create(title=title, content=content, category_id=category_id, image=image, author_id=request.user.id):
                    response_data = {
                        'SType': 'success',
                        'message': "Saved Successfully"
                    }   
            return HttpResponse(json.dumps(response_data), content_type="application/json")  
        elif request.POST.get('deyHidden') == 'category_hidden':
            CatNames = request.POST.getlist('CatName[]')
            for CatName in CatNames:
                Category.objects.get_or_create(CatName=CatName)
            response_data = {
                'SType': 'success',
                'message': "Saved Successfully"
            }                
            return HttpResponse(json.dumps(response_data), content_type="application/json")

    context={
        'form':NewPostForm(),
        'title':'Create Post',
        'category': Category.objects.all()
    }
    return render(request, 'blog/form.html', context)

@login_required
def UpdatePost(request, pk):
    obj = get_object_or_404(Posts, id=pk)
    myForm = NewPostForm(instance = obj)
    if request.method == 'POST':
        myForm = NewPostForm(request.POST, request.FILES, instance=obj)
        response_data = {
            'SType': 'danger',
            'message': "An Error Occured, pls try again later"
        }
        if myForm.is_valid():
            if myForm.save():
                response_data = {
                    'SType': 'success',
                    'message': "Updated Successfully"
                } 
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    context={ 
        'form':myForm,
        'title': obj.title,
        'category': Category.objects.all()
    }
    return render(request, 'blog/update.html', context) 

def PostDetail(request, pk):
    obj = get_object_or_404(Posts, id=pk)
    nextPost = Posts.objects.filter(id__gt=obj.id).order_by('id').first()
    prevPost = Posts.objects.filter(id__lt=obj.id).order_by('-id').first()
    context={ 
        'object':obj,
        'title': obj.title,
        'nextPost': nextPost,
        'prevPost': prevPost,
        'latests': Posts.objects.all().order_by('-id')[:5]
    }
    return render(request, 'blog/details.html', context) 

def index(request):
    posts_list = Posts.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(posts_list, pagNum)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/home.html', { 'posts': posts })

class NewPostView(LoginRequiredMixin, TemplateView):
    template_name = 'blog/form.html'
    deyCat = Category.objects.all()

    def get(self, request, **kwargs):
        context = {
            'form': NewPostForm(),
            'title': 'Create Post',
            'categories': self.deyCat
        }
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        myForm = NewPostForm(request.POST, request.FILES)
        response_data = {
            'SType': 'danger',
            'message': "An Error Occured, pls try again later"
        }
        if request.POST.get('deyHidden') == 'create_hidden':
            title = request.POST.get('title')
            content = request.POST.get('content')
            category_id = request.POST.get('category')
            image = request.FILES.get('image')
            if myForm.is_valid():
                if Posts.objects.create(title=title, content=content, category_id=category_id, image=image,
                                        author_id=request.user.id):
                    response_data = {
                        'SType': 'success',
                        'message': "Saved Successfully"
                    }
            return HttpResponse(json.dumps(response_data), content_type="application/json")
        elif request.POST.get('deyHidden') == 'category_hidden':
            CatNames = request.POST.getlist('CatName[]')
            for CatName in CatNames:
                Category.objects.get_or_create(CatName=CatName)
            response_data = {
                'SType': 'success',
                'message': "Saved Successfully"
            }
            return HttpResponse(json.dumps(response_data), content_type="application/json")

blog/templates/blog/CatPosts.html
{% extends 'base.html' %}

{% block content %}
    {% if posts %}
        <h1 class="mb-3 ml-3"> {{view.kwargs.category}} Category ({{page_obj.paginator.count}})</h1>
    {% else %}
        <h1 class="mb-3 ml-3"> {{view.kwargs.category}} has no post yet </h1>
    {% endif %}
   
    <div class="row justify-content-center">
        <div class="card-columns mb-4">            
            {% for post in posts %}
                <div class="card p-3 shadow" >
                    <img height = "350px" class="card-img-top p-3" src="{{post.image.url}}" alt="">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a class="text-dark" href="{{post.get_absolute_url}}">
                                {{post.title |title }}
                            </a>
                        </h5>
                        <p class="card-text mb-auto">{{post.content |truncatechars:70}}</p>
                        <p class="card-text">
                            <small class="text-muted">
                                By <a href="{% url 'Blog-User' post.author.username %}" >{{post.author.profile.fullName}} </a> on {{post.date_posted | date:"F dS, Y"}}
                            </small>
                        </p>
                        <div class="col-12"><a href="{{post.get_absolute_url}}">Continue reading</a> </div>
                        {% if post.author == user %}
                            <a class="btn btn-outline-danger btn-sm my-1" href="{% url 'Blog-Delete' post.id %}">Delete</a> 
                            <a class="btn btn-outline-secondary btn-sm" href="{% url 'Blog-Update' post.id %}" style="float:right">Update</a> 
                        {% endif %}
                    </div>
                </div> 
            {% endfor %}                
        </div> 
    </div>
    <div class="row"> 
        {% if is_paginated %}
            <nav aria-label="Page " >
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                        <li class="page-item ">
                            <a class="page-link" href="?page=1" tabindex="-1">First</a>
                        </li>
                        <li class="page-item ">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{num}}">{{num}} <span class="sr-only">(current)</span></a>
                            </li>
                        {% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'3' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{num}}">{{num}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" >Next</a>
                        </li>
                        <li class="page-item ">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" >Last</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %} 
    </div>

{% endblock  %}

blog/templates/blog/UserPosts.html
{% extends 'base.html' %}

{% block content %}
   <h1 class="mb-3 ml-3">Post by {{view.kwargs.username}} ({{page_obj.paginator.count}})</h1>
    <div class="row justify-content-center">
        <div class="card-columns mb-4">
            {% for post in posts %}
                <div class="card p-3 shadow" >
                    <img height = "350px" class="card-img-top p-3" src="{{post.image.url}}" alt="">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a class="text-dark" href="{{post.get_absolute_url}}">
                                {{post.title |title }}
                            </a>
                        </h5>
                        <p class="card-text mb-auto">{{post.content |truncatechars:70}}</p>
                        <p class="card-text">
                            <small class="text-muted">
                                By <a href="{% url 'Blog-User' post.author.username %}" >{{post.author.profile.fullName}} </a> on {{post.date_posted | date:"F dS, Y"}}
                            </small>
                        </p>
                        <div class="col-12"><a href="{{post.get_absolute_url}}">Continue reading</a> </div>
                        {% if post.author == user %}
                            <a class="btn btn-outline-danger btn-sm my-1" href="{% url 'Blog-Delete' post.id %}">Delete</a> 
                            <a class="btn btn-outline-secondary btn-sm" href="{% url 'Blog-Update' post.id %}" style="float:right">Update</a> 
                        {% endif %}
                    </div>
                </div> 
            {% endfor %}                
        </div> 
    </div> 
    <div class="row">
        {% if is_paginated %}
            <nav aria-label="" >
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                        <li class="page-item ">
                            <a class="page-link" href="?page=1" tabindex="-1">First</a>
                        </li>
                        <li class="page-item ">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{num}}">{{num}} <span class="sr-only">(current)</span></a>
                            </li>
                        {% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'3' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{num}}">{{num}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" >Next</a>
                        </li>
                        <li class="page-item ">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" >Last</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %} 
    </div> 

{% endblock  %}

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block content %}

    <h2>About Us</h2>

{% endblock  %}

blog/templates/blog/details.html
{% extends 'base.html' %}

{% block content %}

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic ">
                <img class="d-block w-100" src="{{object.image.url}}" >
            </h3>

            <div class="blog-post">
                <h2 class="blog-post-title">{{object.title | title }}</h2>
                <p>
                    {% if object.author == user %}
                        <a class="btn btn-outline-danger my-1" href="{% url 'Blog-Delete' object.id %}">Delete</a> 
                        <a class="btn btn-outline-secondary my-1" href="{% url 'Blog-Update' object.id %}" style="float:right">Update</a> 
                    {% endif %}
                </p>
                <p class="blog-post-meta text-muted">
                    {{object.date_posted | date:"F dS, Y"}} 
                    By <a href="{% url 'Blog-User' object.author.username %}" >{{object.author.profile.fullName}} </a>
                </p>

                <p>{{object.content}}</p>
                
                
            </div>
            <nav class="blog-pagination">
                <a class="btn btn-outline-primary {% if not prevPost.id %} disabled {% endif %}" href="{{prevPost.get_absolute_url}}">Older</a>
                <a class="btn btn-outline-secondary {% if not nextPost.id %} disabled {% endif %}" href="{{nextPost.get_absolute_url}}">Newer</a>
            </nav>

            </div>

            <aside class="col-md-4 blog-sidebar">
                <div class="p-3 mb-3 bg-light rounded">
                    <h4 class="font-italic">About</h4>
                    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>

                <div class="p-3">
                    <h4 class="font-italic">Latest Post</h4>                
                    <ol class="list-unstyled mb-0">
                        {% for latest in latests %}
                            <a style="color:black" href="{{latest.get_absolute_url}}">
                                <li class="media mb-3">
                                    <img class="mr-3 rounded" width="20%" height="auto" src="{{latest.image.url}}" alt="Generic image">
                                    <div class="media-body">
                                    <h6 class="mt-0 mb-1">{{latest.title | title }}</h6>
                                        <p>{{latest.content | truncatechars:30}}</p>
                                    </div>
                                </li>
                            </a>
                        {% endfor %}                        
                    </ol>
                </div>
            </aside>
        </div>
    </main>

{% endblock  %}

blog/templates/blog/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-md-9 col-sm-9 bg-white rounded shadow-lg mt-4 p-5">
        <div class="justify-content-end mb-4">
            <a href="#" data-toggle="modal" data-target="#categoryModal" class="btn btn-md btn-outline-secondary"> Create Category</a>
        </div> 
        <form action="." method="POST" enctype="multipart/form-data" id="PostNew__form"> {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a Blog Post</legend>
                <div class="form-row">
                    <div class="form-group col-md-8 mb-0">
                        {{ form.title | as_crispy_field }}
                    </div>

                    <div class="form-group col-md-4 mb-0">
                        <div id="div_id_category" class="form-group">
                            <label for="id_category" class="col-form-label  requiredField">
                                Category<span class="asteriskField">*</span>
                            </label>
                            <div class="">
                                <select class="form-control" name="category">
                                    {% for category in categories %}
                                        <option value="{{category.id}}">{{category.CatName}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>                
                </div>
                {{ form.content | as_crispy_field }}
                
                <div class="ImgToHide">
                    {{ form.image | as_crispy_field }}
                </div>
                
                <div id="div_id_placeHo" class="form-group">
                    <label for="id_placeHo" class="col-form-label  requiredField">
                        Post Picture<span class="asteriskField">*</span>
                    </label>
                    <div class="">
                        <img class="PoNeImg img-responsive" style="width: 90%;" src="https://via.placeholder.com/270x270?text=Click+Here+To+Change+Image" />
                    </div>
                </div>
                <input type="hidden" name="deyHidden" value="create_hidden"> 
            </fieldset>
            <div class="form-group">
                <h6 id="PostNew__show" ></h6>
                <img src=" {% static 'images/ajax-loader.gif' %}" style="Display:none;" id="PostNew__img">
                <button class="btn btn-outline-info" type="submit"  onclick="submit_form('PostNew__form', 'PostNew__submit', 'PostNew__img', 'PostNew__show', 'yes')" id="PostNew__submit">Create</button>
            </div>
        </form>
    </div>
</div>
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Category</h5>
        
        <button type="button" class="close reloadAm" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <a class="btn addAmBtm mb-2 float-right text-secondary" href="#">Add More</a>
            <form action="." method="post" id="PostCat__form">{% csrf_token %}
                <input type="hidden" name="deyHidden" value="category_hidden">
                <div class="CatNameDiv"><div class="form-group"><input type="text" class="form-control" name="CatName[]" ></div></div>

                <div class="form-group">
                    <h6 id="PostCat__show"></h6>
                    <img src=" {% static 'images/ajax-loader.gif' %}" style="Display:none;" id="PostCat__img">
                    <button type="button" class="btn btn-outline-danger reloadAm" data-dismiss="modal">Close</button>
                    <button class="btn btn-outline-info float-right" type="submit"  onclick="submit_form('PostCat__form', 'PostCat__submit', 'PostCat__img', 'PostCat__show', 'no')" id="PostCat__submit">Create</button>
                </div>
            </form>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function(){
        $('.PoNeImg').click(function(){
            $('#id_image').trigger('click')
        })
        $('.addAmBtm').click(function(e){
            e.preventDefault()
            $('.CatNameDiv').append('<div class="form-group"><input type="text" class="form-control" name="CatName[]" ></div>')
        })
        $('#id_image').change(function(){
            var filePath = $(this).prop('files')[0]
            if (filePath) {
                var fileReader = new FileReader();
                fileReader.onload = function (e) {
                    $(".PoNeImg").attr('src', e.target.result);
                }
                fileReader.readAsDataURL(filePath);
            }
        })
    })
</script>
{% endblock  %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-md-6 col-sm-8 bg-white rounded shadow-lg mt-4 p-5">
        <form action="." method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete</legend>
                <p>Are You sure you want to delete the post "{{object.title}}</p>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'Blog-details' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock  %}

blog/templates/blog/posts_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center mt-4"> 
    <div class="col-md-6 col-sm-8 bg-white rounded shadow-lg mt-4 p-5">
        <form action="." method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete</legend>
                <p>Are You sure you want to delete the post "{{object.title}}</p>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'Blog-details' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock  %}

blog/templates/blog/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-md-9 col-sm-9 bg-white rounded shadow-lg mt-4 p-5">
        <form action="." method="POST" enctype="multipart/form-data" id="PostNew__form"> {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update a Blog Post</legend>
                <div class="form-row">
                    <div class="form-group col-md-8 mb-0">
                        {{ form.title | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.category | as_crispy_field }}
                    </div>                
                </div>
                {{ form.content | as_crispy_field }}
                <div class="ImgToHide">
                    {{ form.image | as_crispy_field }}
                </div>
                
                <div id="div_id_placeHo" class="form-group">
                    <label for="id_placeHo" class="col-form-label  requiredField">
                        Post Picture<span class="asteriskField">*</span>
                    </label>
                    <div class="">
                        <img class="PoNeImg img-responsive" style="width: 90%;" src="https://via.placeholder.com/270x270?text=Click+Here+To+Change+Image" />
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <h6 id="PostNew__show" ></h6>
                <img src=" {% static 'images/ajax-loader.gif' %}" style="Display:none;" id="PostNew__img">
                <button class="btn btn-outline-info float-right" type="submit"  onclick="submit_form('PostNew__form', 'PostNew__submit', 'PostNew__img', 'PostNew__show', 'yes')" id="PostNew__submit">Update</button>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
        
        $('.PoNeImg').click(function(){
            $('#id_image').trigger('click')
        })
        $('.PoNeImg').attr('src', $('#div_id_image > div > a').attr('href'))
        $('#id_image').change(function(){
            var filePath = $(this).prop('files')[0]
            if (filePath) {
                var fileReader = new FileReader();
                fileReader.onload = function (e) {
                    $(".PoNeImg").attr('src', e.target.result);
                }
                fileReader.readAsDataURL(filePath);
            }
        })
    })
</script>
{% endblock  %}